# Generated by Django 3.2.6 on 2022-02-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramaTV',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nameprogram', models.CharField(max_length=60)),
                ('synopsis', models.CharField(max_length=60)),
                ('agegroup', models.IntegerField(default=0)),
                ('host', models.CharField(max_length=60)),
                ('time', models.CharField(max_length=60)),
                ('broadcaster', models.CharField(max_length=60)),
            ],
        ),
    ]
